### ISSUE TITLE
Feature: consider moving js-client deploy logic to the CLI

### ISSUE THREAD

**Issue by erezrokah** [netlify/js-client#157]
At the moment most of the CLI deploy command logic in handled by the `js-client`:
https://github.com/netlify/js-client/blob/9d3945c1bb3f8d96b734f3eca1d90c717fa38558/src/deploy/index.js#L42

This seems out of place for a client that should be wrapping our open-api spec.
Also, it prevents this client from being browser compatible.

It might makes sense to move that logic to the CLI, since we're already implementing some deploy logic in the CLI as a part of edge handlers:
https://github.com/netlify/cli/pull/1244

**Comment by ehmicky** [comment]
:100:

**Comment by erezrokah** [comment]
Doing this would also allow for better error handling as we could `try/catch` on each deploy related operation instead of catching everything here:
https://github.com/netlify/cli/blob/7db9ce56c26d25ca43631daaf5d32c3140e15f6a/src/commands/deploy.js#L228

**Comment by svdoever** [comment]
Please don't - I want to use the deploy logic of this library within my own application but NOT depend on netlify-cli. I'm running within a cramped VM with 200 MB memory (using https://glitch.com), so could NOT use netlify-cli, because installing that package downloads 75MB (mostly due to typescript - Why?!):

```
$ npm ls typescript
netlify-test@1.0.0 /mnt/c/Users/serge/Downloads/netlify
└─┬ netlify@4.9.0
  └─┬ @netlify/zip-it-and-ship-it@1.4.0
    └─┬ precinct@6.3.1
      └─┬ detective-typescript@5.8.0
        └── typescript@3.9.7
```

Top 5 package sizes in netlify-dev:
```
$ du -sh -BK ./node_modules/* | sort -nr
53240K  ./node_modules/typescript
2304K   ./node_modules/lodash
1984K   ./node_modules/@babel
1928K   ./node_modules/string.prototype.trimstart
1928K   ./node_modules/string.prototype.trimend
```

That TypeScript is big, ok, but `trimstart` 2MB, and `trimend` 2MB... wow!

I just see that there is actually the same problem with the current `netlify/js-client` library which depends on the same stuff, so not useable as well!!! Such a pity...

**Comment by erezrokah** [comment]
Thanks for your input @svdoever. See more about package size here https://github.com/netlify/cli/issues/494

**Comment by eduardoboucas** [comment]
Currently, CLI works with two instances of `zip-it-and-ship-it`: one as a direct dependency and another as a transitive dependency via `netlify` (the package published from this repo). This is not ideal and introduces unnecessary complexity and maintenance overhead.

Moving the bundling logic to CLI would consolidate them into one, while at the same time simplifying the `netlify` package, making it simply a wrapper over our Open API spec, as @erezrokah pointed out.

**Comment by erquhart** [comment]
Potentially related: https://github.com/netlify/js-client/issues/229

**Comment by eduardoboucas** [comment]
This logic has now been moved to the CLI. We now need to remove the logic from this package and release a new major version.

**Comment by South-Paw** [comment]
How we we call the `deploy` method programmatically in from the cli package?

`netlify/cli` doesn't appear to be a package I can just import into my code and call `deploy` after creating a client like I could before - so this was hardly a 1-1 trade off

**Comment by erezrokah** [comment]
> How we we call the `deploy` method programmatically in from the cli package?

Hi @South-Paw, would spawning the CLI as an external process work?
e.g.
```js
const execa = require('execa');
const { stdout } = await execa.command('netlify deploy', { preferLocal: true });
// do something with stdout
```

You can also pass `NETLIFY_AUTH_TOKEN` and `NETLIFY_SITE_ID` as environment variables.

If that doesn't cover your use case, can you please open a [feature request](https://github.com/netlify/cli/issues/new?assignees=&labels=type%3A+feature&template=feature_request.md&title=Please+replace+with+a+clear+and+descriptive+title) on the CLI repo?

**Comment by South-Paw** [comment]
Hi @erezrokah, thank you for the reply. I'm unsure if spawning a process for the deployment suits the use case?

The deploy is in [the middle of a GitHub action](https://github.com/South-Paw/action-netlify-deploy/blob/07ce8475462daf885db65d4450cee7ebcf5b2943/src/main.ts#L84) which also manages the Netlify deploy messages, comments on the PR/Commit, creating GitHub deploy environments.

Any advice would be appreciated, I'm more than happy to open a feature request if that's the next best step.

**Comment by erezrokah** [comment]
Hi @South-Paw, I actually think using the CLI would provide a better experience.

Users won't need to configure `build-dir`, `functions-dir` and `config-path` as the CLI [resolves those](https://github.com/netlify/cli/blob/172bd1ec80ed1d63157be7a9123c7d3f61fd6524/src/utils/command.js#L146) based on the user's repo.

You can pass a `json` flag to have parsable output and a `message` flag to set the message. `netlify deploy` does draft deploys by default so you can pass `prod` for non drafts.

As for the performance considerations - I think the time it takes to spawn the process should be negligible compared to the time it takes to deploy, but if you experience otherwise it would be great if you can share it.

**Comment by IanVS** [comment]
I'm trying to figure out how to use the cli in a GitHub action.  It's not straightforward, because GitHub says that actions should not rely on any other binaries that aren't preinstalled in their worker boxes.  Do you have any ideas, @erezrokah?  I think you're right that using the automatic resolution features of the cli wou5 be nice, I'm just not sure how to bundle the cli along with my JavaScript action (I don't want to use a docker action in my situation).

**Comment by erezrokah** [comment]
Hi @IanVS, you can install the CLI as a regular dependency, e.g. via `npm install netlify-cli`, then with whatever tool you use to bundle the action, make sure it bundles the CLI.

**Comment by IanVS** [comment]
Thanks @erezrokah.  Do you have any suggestions for bundling a binary out of node_modules into an executable?  I've tried https://github.com/vercel/pkg and https://github.com/vercel/ncc without luck so far.

**Comment by South-Paw** [comment]
> It's a shame that https://github.com/netlify/actions seems to be a dead project with outdated docker files. I'm thinking that there's no good way to build a netlify github action without docker now that deploy has been removed from the js client. And docker actions only run on linux and are slower than javascript actions.

Yeah, echoing a lot of what I've found after switching over the using [netlify/actions](netlify/actions) @IanVS instead of [South-Paw/action-netlify-deploy](https://github.com/South-Paw/action-netlify-deploy). The readme's are also out of date, PRs that update them haven't been merged and there are typo's in the scripts and bugs & gaps in the action outputs to top it off! 😆

The netlify/actions & netlify/cli add about [1-2 mins of extra time to an action](https://user-images.githubusercontent.com/2154764/142083401-b3ecb734-8206-462c-8428-2e19eea2883f.png) because they have to build themselves in the workflow every run instead of being packaged and ready to roll as the JavaScript actions that used `deploy` from the cli were. This is obviously resulting in a small amount of wasted action minutes every month for organisations as well 😞
