### ISSUE TITLE
Update concurrentUpload

### ISSUE THREAD

**Issue by kaganjd** [netlify/js-client#178]
**Placeholder/possible dupe related to other concurrency work: https://github.com/netlify/bitballoon/issues/5842 (internal)**

Someone in Community recently pointed out that we show concurrentUpload as 15:
https://github.com/netlify/js-client/blob/9915239d6931c49416feda94dfc013eec7e0ff1a/src/deploy/index.js#L23

when it is actually 5. This person was using 15 and getting rate-limited.

**Comment by ingride** [comment]
yep, we should do this. 

With the concurrency limits on the API side, we didn't prioritize this because there would be no major impact on deploys and we shouldn't see any issues. @kaganjd if you wanna cut a PR, am all up for it and then we can cut a release with the change.

Otherwise I can do tomorrow

**Comment by ingride** [comment]
this has been fixed in https://github.com/netlify/js-client/pull/181
