### ISSUE TITLE
Feature: drop Node.js 8 support

### ISSUE THREAD

**Issue by erezrokah** [netlify/js-client#270]
Following up with https://github.com/netlify/cli/issues/1568, we should be good now with dropping Node.js 8 support for the `js-client`.

**Comment by ehmicky** [comment]
I am thinking we might want to drop support for Node 8 from `@netlify/build` and `@netlify/config` first since they use `js-client` (to retrieve site information, cancel builds and report plugins statuses).

The only parts which use `js-client` should use Node version 12 in production.
However, the tests are currently running `@netlify/build` and `@netlify/config` in Node 8. We do this to test the case where sites would set a custom Node.js version with Node 8. We could change the tests to run two Node versions instead (Node 12 for the core + Node 8/14 for the plugins) though. Or we could drop Node 8 support from `@netlify/build` first. What do you think?

**Comment by erezrokah** [comment]
We could wait for `@netlify/build` and `@netlify/config`.
I'm not sure we should invest the time to change the tests unless we have an urgent reason to drop Node.js 8 for `js-client`.

**Comment by JGAntunes** [comment]
With https://github.com/netlify/build/issues/3321 underway, adding this to our up next queue as we deprecate Node 8 across `@netlify/build`'s ecosystem.

**Comment by JGAntunes** [comment]
This has been closed via #464
