### ISSUE TITLE
Clarity on disposition towards semver and breaking changes

### ISSUE THREAD

**Issue by jimniels** [netlify/js-client#331]
I recently realized I was running a version of this JS client back at v2. The most recent is v6. This immediately struck terror in my heart that I'd have to consider parsing the release notes from 3 to 4 to 5 to 6 to see what changed.

After looking at the CHANGELOG, I saw nothing mentioning breaking changes. Still, I had gone from v2 to v6 and the upgrade seemed scary. After searching the issues, I still saw nothing about breaking changes and decided to just go for it. Upgrading v2 to v6 seemed to work just fine.

It'd be nice if there was some clarity stated on the project about what major version changes for this tool mean, if anything, to the consumer of this library. Even there was something at the top of the CHANGELOG, for example, that said "Don't worry, any major version bump in this tool means nothing to you. Only worry about the Netlify API itself changing (which would likely mean a new tool anyway). Carry on." Or something like that.

I just have no idea what bumping from v2 to v6 meant for me as someone who has scripts which use this tool. Apparently it meant nothing.

**Comment by erezrokah** [comment]
Hi @jimniels, I agree completely. Since the last major version we've started using conventional commits and release PRs to automatically create the changelog and report breaking changes.
See example autogenerated PR https://github.com/netlify/js-client/pull/330.
We haven't had a breaking change yet, but you can see an example here https://github.com/netlify/framework-info/pull/138

Does that address your concerns?

**Comment by jimniels** [comment]
@erezrokah thanks for the details. The conventional commits and release PRs sound like a great improvement, props to the team!

I guess my biggest concern centered around not being able to find breaking change documentation in the CHANGELOG. I was expecting something like you pointed out:
 
![Screen Shot 2021-02-22 at 9 46 28 AM](https://user-images.githubusercontent.com/1316441/108740382-d76bb580-74f2-11eb-86de-9d23f47cc6ed.png)

But when I went through versions 3, 4, 5, and 6, I found nothing in the CHANGELOG. For each major version change, that made me wonder either:

1. There are breaking changes, they just didn't document them.
2. There are no breaking changes, they just changed major version numbers for _some_ reason?

To your point—“We haven't had a breaking change yet”—it sounds like number 2 above.

What would've helped make this more clear to me would've been to:

1. Don't do a major version bump unless there are breaking changes in the tool’s API
2. If you do a major version bump that doesn't have breaking changes, explicitly call that out in the CHANGELOG, i.e.

![Screen Shot 2021-02-22 at 9 52 22 AM](https://user-images.githubusercontent.com/1316441/108741178-ab046900-74f3-11eb-9e4a-a3bba7390a94.png)

To your question, something like that would address my concerns and would've made my upgrade much less anxiety ridden ha :)

Thank you for asking that I clarify my impetus to create this issue.

**Comment by erezrokah** [comment]
> To your point—“We haven't had a breaking change yet”—it sounds like number 2 above.

Clarifying this - I should have written `We haven't had a breaking change since we introduced the new process using conventional commits and release PR`.

So I think we're on the same page here going forward. Thank you for opening the issue.
Closing as I believe it is addressed - please comment if you have any other concerns/questions.
